#!/bin/sh -ex

. inc/common

juju-log "Installing software"

apt-get update
apt-get -y install --no-install-suggests --no-install-recommends  apache2 php5-gd libapache2-mod-php5 mysql-client-core-5.5 php5-mysql php5-mcrypt php5-curl pwgen exim4-daemon-light

sed -i "s|dc_eximconfig_configtype='local'|dc_eximconfig_configtype='internet'|g" /etc/exim4/update-exim4.conf.conf

update-exim4.conf



a2enmod php5 headers
a2dissite 000-default

php5enmod mcrypt
php5enmod curl

service apache2 restart

juju-log "Download"

MAGENTO_TARBALL="http://www.magentocommerce.com/downloads/assets/1.9.1.0/magento-1.9.1.0.tar.gz"

mkdir -p $install_path

curl -vv -L $MAGENTO_TARBALL > $install_path/magento.tar.gz

juju-log "Extract"


tar -zxvf $install_path/magento.tar.gz

cd $install_path

mv magento/* magento/.htaccess .
chmod -R o+w media var
chmod o+w app/etc

rm -f $install_path/magento.tar.gz


# Secret key for configuring Joomla
#secret_key=`pwgen 32 1`
#sed -i "s|public \$secret = '.*';|public \$secret = '"$secret_key"';|g" $install_path/installation/configuration.php-dist

# Set better file permissions
# set_permissions
